---
title: "Addition Financial Competition"
author: "Kyle Brinker"
date: "2024-11-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Essential Question: The primary objective of this endeavor is to accurately predict and make well-informed decisions about the critical factors influencing consumer choices when selecting a financial institution for mortgage loans. This analysis aims to leverage publicly available HMDA data, consumer reviews, financial ratings, and industry reports to uncover patterns and trends in consumer behavior.

#Clear Workspace and establish parameters
options(
  digits = 2,
  scipen = 999,
  warn = -1
)
rm(
  list = ls()
)

#Initiate necessary packages
library(magrittr)
library(dplyr)
library(fastDummies)
library(ggplot2)
```

```{r}
#Upload Data
#HMDA(Please replace file path with the file path of the data on your device)
loans.df <- read.csv("F:\\Addition Financial Competition\\2023_public_lar_csv\\2023_public_lar_csv.csv")
#Complaints (Please replace file path with the file path of the data on your device)
complaints.df <- read.csv("F:\\Addition Financial Competition\\complaints.csv\\complaints.csv")%>%
  na.omit() %>%
  as.data.frame()
#Seperate the numerical data in the HMDA dataset
loans_numerical.df <- loans.df %>%
  dplyr::select("derived_msa_md", "loan_amount","interest_rate","origination_charges","loan_term","property_value","income","tract_population","tract_minority_population_percent","ffiec_msa_md_median_family_income","tract_to_msa_income_percentage","tract_owner_occupied_units","tract_one_to_four_family_homes","tract_median_age_of_housing_units")%>%
  na.omit() %>%
  lapply(as.numeric) %>%
  as.data.frame()
```

```{r}
#NPCA
scaled_loans_numerical <- scale(loans_numerical.df) %>%
  na.omit()
xnpca<- princomp(scaled_loans_numerical, cor=T);
plot(xnpca);
loadings(xnpca);
```
```{r}
#Factor Analysis
# Maximum Likelihood Factor Analysis without varimax rotation factanal performs
mlm  <- factanal(scaled_loans_numerical, 2, rotation = "varimax", covmat = cor(scaled_loans_numerical));
load <- mlm$loadings; # estimated factor loadings
ld   <-  cbind(load[, 1], load[, 2]); # the estimated factor loadings matrix
com  <- diag(ld %*% t(ld)); # communalities are calculated
psi  <- diag(cor(scaled_loans_numerical)) - diag(ld %*% t(ld));  # specific variances are calculated
tbl  <- cbind(load[, 1], load[, 2], com, psi);

# plot first factor against second
plot(load[, 1], load[, 2], type = "n", xlab = "Factor 1", ylab = "Factor 2", main = "Factors21 - theta21",
    font.main = 1, cex.lab = 1.1, cex.axis = 1.1, cex.main = 1.4, ylim = c(-1, +1));
text(load[, 1], load[, 2], colnames(scaled_loans_numerical), cex = 0.7);
abline(h = 0, v = 0);
```

```{r}
#Newton-Raphson (Assume normal distribution due to scaling and only numerical target variables)
numerical_scaled_loans.train <- scaled_loans_numerical[1:1000, ]
x.train <- as.matrix(cbind(1, numerical_scaled_loans.train[,-2]))
y.train <- as.matrix(numerical_scaled_loans.train[,2])
beta_t_1 <- as.matrix(rep(1, 14))
beta_t <- as.matrix(rep(0, 14))
while (max(abs(beta_t_1 - beta_t)) > 0.000001){
  beta_t<-beta_t_1
  gradient <- -t(x.train)%*%(y.train-x.train%*%beta_t)
  H <- t(x.train)%*%x.train
  beta_t_1 <- beta_t-solve(H)%*%gradient
}
beta_t_1
```

```{r}
#Feature Importance
# Lasso
#Cross validation to find the optimal lambda
cv.glmnet_lasso <- glmnet::cv.glmnet(
  x = x.train %>%
    as.matrix(),
  y = y.train%>%
    as.matrix(),
  alpha = 1
)
cv.glmnet_lasso$lambda.min

#Lasso Model using Lambda within 1 Standard Error
glmnet_lasso <- glmnet::glmnet(
  x = x.train %>%
    as.matrix(),
  y = y.train%>%
    as.matrix(),
  alpha = 1,
  lambda = cv.glmnet_lasso$lambda.min
)

coef(
  object = glmnet_lasso
) %>%
  as.matrix() %>%
  as.data.frame() %>%
  dplyr::arrange(s0)

#Ridge
#Finding the Optimal value of Lambda
cv.glmnet_ridge <- glmnet::cv.glmnet(
  x = x.train %>%
    as.matrix(),
  y = y.train%>%
    as.matrix(),
  alpha = 0.5
)
cv.glmnet_ridge$lambda.min

glmnet_ridge <- glmnet::glmnet(
  x = x.train %>%
    as.matrix(),
  y = y.train%>%
    as.matrix(),
  alpha = 0,
  lambda = cv.glmnet_ridge$lambda.min
)

coef(
  object = glmnet_ridge
) %>%
  as.matrix() %>%
  as.data.frame() %>%
  dplyr::arrange(s0)

#Elastic Net
#Finding the Optimal value of Lambda
cv.glmnet_elasticnet <- glmnet::cv.glmnet(
  x = x.train %>%
    as.matrix(),
  y = y.train%>%
    as.matrix(),
  alpha = 0.5
)
cv.glmnet_elasticnet$lambda.min

glmnet_elasticnet <- glmnet::glmnet(
  x = x.train %>%
    as.matrix(),
  y = y.train%>%
    as.matrix(),
  alpha = 0.5,
  lambda = cv.glmnet_elasticnet$lambda.min
)

coef(
  object = glmnet_elasticnet
) %>%
  as.matrix() %>%
  as.data.frame() %>%
  dplyr::arrange(s0)
```

```{r}
#Seperate qualitative predictors from HMDA dataset
loans_categorical.df <- loans.df %>%
  dplyr::select(
    -c("interest_rate", "property_value","tract_population", "tract_minority_population_percent", "ffiec_msa_md_median_family_income", 
       "tract_to_msa_income_percentage", "tract_owner_occupied_units", "tract_one_to_four_family_homes", 
       "tract_median_age_of_housing_units")
  ) %>%
  as.data.frame()

#Assign the data points that occur within each predictor column as "Other" to reduce the number of dummy variables
temp.df <- loans_categorical.df
for(j in colnames(temp.df)) temp.df[is.na(temp.df[,j]),j] <- "N/A"
for(j in colnames(temp.df)){
  v <- temp.df[,j] %>%
    table() %>%
    prop.table()
  v <- names(v)[v > 0.05]
  temp.df[!temp.df[,j] %in% v,j] <- "Other"
}
#Establish new columns as a dataframe
temp.df <- temp.df %>%
  as.data.frame()

#Create dummy variables
loans_categorical.df <- temp.df %>%
  fastDummies::dummy_cols(remove_selected_columns = TRUE) %>%
  as.data.frame()

#Combine the predictors with dummy variables with the borrowing amount target variable
borrowing <- loans.df$loan_amount
loans_categorical.df <- cbind(loans_categorical.df,borrowing) %>%
  as.data.frame()

#Full Model
glm_full <- glm(
  formula = borrowing ~ .,
  data = loans_categorical.df
)

#Feature Selection Using Forward Stepwise
step_forward = step(
  object = glm_full,
  direction = "forward"
)

#Reduced Model
glm_reduced <- glm(
  formula = borrowing ~ activity_year + lien_status + construction_method + 
    lei_Other + derived_msa_md_99999 + derived_msa_md_Other + 
    state_code_CA + state_code_FL + state_code_Other + state_code_TX + 
    county_code_Other + census_tract_Other + conforming_loan_limit_C + 
    conforming_loan_limit_Other + `derived_loan_product_type_Conventional:First Lien` + 
    `derived_loan_product_type_Conventional:Subordinate Lien` + 
    `derived_loan_product_type_FHA:First Lien` + derived_loan_product_type_Other + 
    `derived_loan_product_type_VA:First Lien` + derived_dwelling_category_Other + 
    `derived_dwelling_category_Single Family (1-4 Units):Manufactured` + 
    `derived_dwelling_category_Single Family (1-4 Units):Site-Built` + 
    `derived_ethnicity_Ethnicity Not Available` + `derived_ethnicity_Hispanic or Latino` + 
    `derived_ethnicity_Not Hispanic or Latino` + derived_ethnicity_Other + 
    derived_race_Asian + `derived_race_Black or African American` + 
    derived_race_Other + `derived_race_Race Not Available` + 
    derived_race_White + derived_sex_Female + derived_sex_Joint + 
    derived_sex_Male + `derived_sex_Sex Not Available` + action_taken_1 + 
    action_taken_3 + action_taken_4 + action_taken_6 + action_taken_Other + 
    purchaser_type_0 + purchaser_type_1 + purchaser_type_2 + 
    purchaser_type_3 + purchaser_type_71 + purchaser_type_Other + 
    preapproval_2 + preapproval_Other + loan_type_1 + loan_type_2 + 
    loan_type_3 + loan_type_Other + loan_purpose_1 + loan_purpose_2 + 
    loan_purpose_4 + loan_purpose_31 + loan_purpose_32 + loan_purpose_Other + 
    reverse_mortgage_2 + reverse_mortgage_Other + open_end_line_of_credit_1 + 
    open_end_line_of_credit_2 + open_end_line_of_credit_Other + 
    business_or_commercial_purpose_1 + business_or_commercial_purpose_2 + 
    business_or_commercial_purpose_Other + loan_amount_Other + 
    combined_loan_to_value_ratio_80.0 + `combined_loan_to_value_ratio_N/A` + 
    combined_loan_to_value_ratio_Other + `rate_spread_N/A` + 
    rate_spread_Other + hoepa_status_2 + hoepa_status_3 + hoepa_status_Other + 
    `total_loan_costs_N/A` + total_loan_costs_Other + `total_points_and_fees_N/A` + 
    total_points_and_fees_Other + origination_charges_0.0 + `origination_charges_N/A` + 
    origination_charges_Other + discount_points_ + `discount_points_N/A` + 
    discount_points_Other + lender_credits_ + `lender_credits_N/A` + 
    lender_credits_Other + loan_term_180 + loan_term_300 + loan_term_360 + 
    loan_term_Other + `prepayment_penalty_term_N/A` + prepayment_penalty_term_Other + 
    intro_rate_period_1 + `intro_rate_period_N/A` + intro_rate_period_Other + 
    negative_amortization_2 + negative_amortization_Other + interest_only_payment_1 + 
    interest_only_payment_2 + interest_only_payment_Other + balloon_payment_2 + 
    balloon_payment_Other + other_nonamortizing_features_2 + 
    other_nonamortizing_features_Other + occupancy_type_1 + occupancy_type_3 + 
    occupancy_type_Other + manufactured_home_secured_property_type_3 + 
    manufactured_home_secured_property_type_Other + manufactured_home_land_property_interest_5 + 
    manufactured_home_land_property_interest_Other + total_units_1 + 
    total_units_Other + `multifamily_affordable_units_N/A` + 
    multifamily_affordable_units_Other + `income_N/A` + income_Other + 
    `debt_to_income_ratio_>60%` + `debt_to_income_ratio_20%-<30%` + 
    `debt_to_income_ratio_30%-<36%` + `debt_to_income_ratio_50%-60%` + 
    `debt_to_income_ratio_N/A` + debt_to_income_ratio_Other + 
    applicant_credit_score_type_1 + applicant_credit_score_type_2 + 
    applicant_credit_score_type_3 + applicant_credit_score_type_8 + 
    applicant_credit_score_type_9 + applicant_credit_score_type_Other + 
    co_applicant_credit_score_type_9 + co_applicant_credit_score_type_10 + 
    co_applicant_credit_score_type_Other + applicant_ethnicity_1_1 + 
    applicant_ethnicity_1_2 + applicant_ethnicity_1_3 + applicant_ethnicity_1_4 + 
    applicant_ethnicity_1_Other + `applicant_ethnicity_2_N/A` + 
    applicant_ethnicity_2_Other + `applicant_ethnicity_3_N/A` + 
    applicant_ethnicity_3_Other + `applicant_ethnicity_4_N/A` + 
    applicant_ethnicity_4_Other + `applicant_ethnicity_5_N/A` + 
    applicant_ethnicity_5_Other + co_applicant_ethnicity_1_2 + 
    co_applicant_ethnicity_1_3 + co_applicant_ethnicity_1_4 + 
    co_applicant_ethnicity_1_5 + co_applicant_ethnicity_1_Other + 
    `co_applicant_ethnicity_2_N/A` + co_applicant_ethnicity_2_Other + 
    `co_applicant_ethnicity_3_N/A` + co_applicant_ethnicity_3_Other + 
    `co_applicant_ethnicity_4_N/A` + co_applicant_ethnicity_4_Other + 
    `co_applicant_ethnicity_5_N/A` + co_applicant_ethnicity_5_Other + 
    applicant_ethnicity_observed_2 + applicant_ethnicity_observed_3 + 
    applicant_ethnicity_observed_Other + co_applicant_ethnicity_observed_2 + 
    co_applicant_ethnicity_observed_3 + co_applicant_ethnicity_observed_4 + 
    co_applicant_ethnicity_observed_Other + applicant_race_1_3 + 
    applicant_race_1_5 + applicant_race_1_6 + applicant_race_1_7 + 
    applicant_race_1_Other + `applicant_race_2_N/A` + applicant_race_2_Other + 
    `applicant_race_3_N/A` + applicant_race_3_Other + `applicant_race_4_N/A` + 
    applicant_race_4_Other + `applicant_race_5_N/A` + applicant_race_5_Other + 
    co_applicant_race_1_5 + co_applicant_race_1_6 + co_applicant_race_1_7 + 
    co_applicant_race_1_8 + co_applicant_race_1_Other + `co_applicant_race_2_N/A` + 
    co_applicant_race_2_Other + `co_applicant_race_3_N/A` + co_applicant_race_3_Other + 
    `co_applicant_race_4_N/A` + co_applicant_race_4_Other + `co_applicant_race_5_N/A` + 
    co_applicant_race_5_Other + applicant_race_observed_2 + applicant_race_observed_3 + 
    applicant_race_observed_Other + co_applicant_race_observed_2 + 
    co_applicant_race_observed_3 + co_applicant_race_observed_4 + 
    co_applicant_race_observed_Other + applicant_sex_1 + applicant_sex_2 + 
    applicant_sex_3 + applicant_sex_4 + applicant_sex_Other + 
    co_applicant_sex_1 + co_applicant_sex_2 + co_applicant_sex_4 + 
    co_applicant_sex_5 + co_applicant_sex_Other + applicant_sex_observed_2 + 
    applicant_sex_observed_3 + applicant_sex_observed_Other + 
    co_applicant_sex_observed_2 + co_applicant_sex_observed_3 + 
    co_applicant_sex_observed_4 + co_applicant_sex_observed_Other + 
    `applicant_age_25-34` + `applicant_age_35-44` + `applicant_age_45-54` + 
    `applicant_age_55-64` + `applicant_age_65-74` + applicant_age_8888 + 
    applicant_age_Other + `co_applicant_age_25-34` + `co_applicant_age_35-44` + 
    `co_applicant_age_45-54` + `co_applicant_age_55-64` + co_applicant_age_8888 + 
    co_applicant_age_9999 + co_applicant_age_Other + `applicant_age_above_62_N/A` + 
    applicant_age_above_62_No + applicant_age_above_62_Yes + 
    `co_applicant_age_above_62_N/A` + co_applicant_age_above_62_No + 
    co_applicant_age_above_62_Yes + submission_of_application_1 + 
    submission_of_application_2 + submission_of_application_3 + 
    submission_of_application_Other + initially_payable_to_institution_1 + 
    initially_payable_to_institution_3 + initially_payable_to_institution_Other + 
    aus_1_1 + aus_1_2 + aus_1_3 + aus_1_6 + aus_1_Other + `aus_2_N/A` + 
    aus_2_Other + `aus_3_N/A` + aus_3_Other + `aus_4_N/A` + aus_4_Other + 
    `aus_5_N/A` + aus_5_Other + denial_reason_1_1 + denial_reason_1_3 + 
    denial_reason_1_10 + denial_reason_1_Other + `denial_reason_2_N/A` + 
    denial_reason_2_Other + `denial_reason_3_N/A` + denial_reason_3_Other + 
    `denial_reason_4_N/A` + denial_reason_4_Other
  data = loans_categorical.df
)

sort(glm_reduced$coefficients)
```

```{r}
#Complaints data with mortgage loans filtered
mortgage_complaints <- complaints.df %>% 
  filter(Product == "Mortgage")

#Create a count of the most common issues for mortgages
mortgage_complaints_plot <- mortgage_complaints %>%
  dplyr::group_by(Issue) %>%
  dplyr::summarise(
    Count = dplyr::n()
  ) %>%
  dplyr::ungroup() %>%
  dplyr::mutate(
    Percent = 100*Count/sum(Count),
    Label = paste0(Count,", ",round(Percent),"%")
  )

#Create a bar graph of the most common issues for mortgage loans
mortgage_complaints_plot %>%
  ggplot() + 
  aes(y = Issue, x = Count, label = Label, fill = Issue) +   # Swap x and y for horizontal plot
  geom_col() + 
  geom_text(position = position_stack(vjust = 0.5), size = 3.5, color = "white") +  # Adjust text placement
  theme_bw() +
  theme(
    axis.text.y = element_text(angle = 0, hjust = 1),  # Ensure the y-axis labels are readable
    plot.margin = margin(10, 10, 10, 10),  # Add margins for spacing
    legend.position = "none",  # Remove legend if not needed
    plot.title = element_text(size = 16, face = "bold"),  # Title styling
    axis.title.x = element_text(size = 12),  # X-axis title styling
    axis.title.y = element_text(size = 12)   # Y-axis title styling
  ) +
  labs(title = "Mortgage Complaints", x = "Count", y = "Issue")
```